[tool.poetry]
name = "pyspark-study"
version = "0.1.0"
description = ""
authors = ["Gabriel Soares Campanário <gabriel.camp96@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
findspark = "^2.0.1"
numpy = "^1.22.2"
pyspark = "^3.2.1"
matplotlib = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
